common_environment: &common_environment
  docker:
    - image: circleci/node:10.14
  working_directory: ~/redux-freeform

cache_keys: &cache_keys
  keys:
    - citybaseinc-redux-freeform-v1-yarn-{{ checksum "yarn.lock" }}-{{ .Branch }}
    - citybaseinc-redux-freeform-v1-yarn-{{ checksum "yarn.lock" }}
    - citybaseinc-redux-freeform-v1

cache_paths: &cache_paths
  paths:
    - ~/.cache/yarn
    - ~/.cache/npm
    - node_modules

save_cache_map: &save_cache_map
  <<: *cache_paths
  name: Persist Node Cache

test_steps: &test_steps
  - checkout
  - restore_cache: *cache_keys
  - run: yarn install
  - save-cache:
      <<: *save_cache_map
      key: citybaseinc-redux-freeform-v1-yarn-{{ checksum "yarn.lock" }}-{{ .Branch }}
  - save-cache:
      <<: *save_cache_map
      key: citybaseinc-redux-freeform-v1-yarn-{{ checksum "yarn.lock" }}
  - save-cache:
      <<: *save_cache_map
      key: citybaseinc-redux-freeform-v1
  - run: yarn test

coverage_steps: &coverage_steps
  - checkout
  - restore_cache: *cache_keys
  - run: yarn install
  - run: yarn coverage

deploy_docs_steps: &deploy_docs_steps
  - checkout
  - restore_cache: *cache_keys
  - run: yarn install
  - run:
      name: Deploying to GitHub Pages
      command: |
        git config --global user.email "liam-cb@users.noreply.github.com"
        git config --global user.name "liam-cb"
        echo "machine github.com login liam-cb password $GITHUB_TOKEN" > ~/.netrc
        cd website && yarn install && GIT_USER=liam-cb yarn run publish-gh-pages

jobs:
  test:
    <<: *common_environment
    steps: *test_steps
  coverage:
    <<: *common_environment
    steps: *coverage_steps
  deploy_docs:
    <<: *common_environment
    steps: *deploy_docs_steps

only_healthy_master: &only_healthy_master
  filters:
    branches:
      only:
        - master
  requires:
    - test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - coverage: *only_healthy_master
      - deploy_docs: *only_healthy_master
