name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: yarn install
        run: |
          yarn install
      - name: yarn test
        run: |
          yarn test
      - name: yarn coverage
        run: |
          yarn coverage
      - name: yarn format-check
        run: |
          yarn format-check
      - name: yarn lint
        run: |
          yarn lint
