name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: yarn install
        run: |
          yarn install
      - name: yarn test
        run: |
          yarn test
      - name: yarn coverage
        run: |
          yarn coverage

